### ISSUE TITLE
Clone address is incorrect

### ISSUE THREAD

**Issue by Georg-M** [NordicSemiconductor/nrf-udev#3] opened 2019-03-08 08:57 UTC
Colon symbol instead of slash in cloning address
And `https://` is missed there:
`git@github.com:NordicSemiconductor/nrf-udev.git`

See screenshot:
![image](https://user-images.githubusercontent.com/22838370/54018015-4f1e6980-4190-11e9-9cf6-daf049eb965a.png)

Please, close this issue, if it is not possible to reproduce.

**Comment by IvanSanchez** [comment] 2019-03-08 10:05
This is a feature, not a bug. See https://serverfault.com/questions/832899/difference-between-https-git-clone-and-ssh-git-clone

**Comment by bihanssen** [comment] 2019-03-08 11:48
Thanks Ivan.
Closing the issue.

**Closed as completed by bihanssen** 2019-03-08 11:48 UTC
